Support Default Credentail Provider
quarkiverse/quarkus-logging-cloudwatch pull request #441
Opened 2023-07-10 04:38 UTC by mavanidipen365

2023-07-10 06:52 UTC, bennetelli commented
Please format both files. We are getting a failed build with this message:
Error:  Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.23.0:validate (default-cli) on project quarkus-logging-cloudwatch: File '/home/runner/work/quarkus-logging-cloudwatch/quarkus-logging-cloudwatch/runtime/src/main/java/io/quarkiverse/logging/cloudwatch/auth/CloudWatchCredentialsProvider.java' has not been previously formatted. Please format file (for example by invoking `mvn -f runtime net.revelc.code.formatter:formatter-maven-plugin:2.23.0:format`) and commit before running validation! -> [Help 1]

2023-07-10 06:53 UTC, bennetelli requested changes

2023-07-10 06:53 UTC, bennetelli commented on runtime/src/main/java/io/quarkiverse/logging/cloudwatch/auth/CloudWatchCredentialsProvider.java
> +//*
please remove this additional /

2023-07-10 09:36 UTC, gwenneg reviewed
Thank you for your contribution @mavanidipen365.

Could you please add a new entry in [config.adoc](https://github.com/quarkiverse/quarkus-logging-cloudwatch/blob/main/docs/modules/ROOT/pages/config.adoc) to document the new config property?

2023-07-10 09:36 UTC, gwenneg commented on runtime/src/main/java/io/quarkiverse/logging/cloudwatch/LoggingCloudWatchConfig.java
> +    @ConfigItem(name = "credentials.provider.type.default", defaultValue = "false")
Let's match the usual naming convention for config properties:
```suggestion
    @ConfigItem(name = "quarkus.log.cloudwatch.default-credentials-provider.enabled", defaultValue = "false")
```

2023-07-10 19:13 UTC, mavanidipen365 commented
Hi @bennetelli and @gwenneg requested changes are incorporated now

2023-07-11 11:27 UTC, bennetelli commented
> Hi @bennetelli and @gwenneg requested changes are incorporated now

Please run: mvn -f runtime net.revelc.code.formatter:formatter-maven-plugin:2.23.0:format
So the build isn't failing anymore. I am not allowed to format it.

2023-07-11 14:36 UTC, mavanidipen365 commented
> > Hi @bennetelli and @gwenneg requested changes are incorporated now
> 
> Please run: mvn -f runtime net.revelc.code.formatter:formatter-maven-plugin:2.23.0:format So the build isn't failing anymore. I am not allowed to format it.

I've applied the formatter and also given access to repo

2023-07-11 14:57 UTC, bennetelli requested changes

2023-07-12 13:54 UTC, mavanidipen365 commented on runtime/src/main/java/io/quarkiverse/logging/cloudwatch/LoggingCloudWatchConfig.java
> +    @ConfigItem(name = "quarkus.log.cloudwatch.default-credentials-provider.enabled", defaultValue = "false")
I've tested on my setup, we don't needed to add prefix

2023-07-12 15:43 UTC, gwenneg commented on runtime/src/main/java/io/quarkiverse/logging/cloudwatch/LoggingCloudWatchConfig.java
> +    @ConfigItem(name = "quarkus.log.cloudwatch.default-credentials-provider.enabled", defaultValue = "false")
My bad, `default-credentials-provider.enabled` should be enough indeed.

2023-07-12 16:03 UTC, mavanidipen365 commented on runtime/src/main/java/io/quarkiverse/logging/cloudwatch/LoggingCloudWatchConfig.java
> +    @ConfigItem(name = "quarkus.log.cloudwatch.default-credentials-provider.enabled", defaultValue = "false")
@gwenneg you are right only default-credentials-provider.enabled is needed
I've tested by removing prefix
please see https://github.com/quarkiverse/quarkus-logging-cloudwatch/pull/441/commits/f07379eec5bdfb251054833d89ebece4930518c3

2023-07-17 07:44 UTC, mavanidipen365 commented on runtime/src/main/java/io/quarkiverse/logging/cloudwatch/LoggingCloudWatchConfig.java
> +    @ConfigItem(name = "quarkus.log.cloudwatch.default-credentials-provider.enabled", defaultValue = "false")
Hi @gwenneg and @bennetelli 
Does any pending changes required by me?

2023-08-16 09:18 UTC, bennetelli approved these changes

2023-08-16 09:19 UTC, merged